CREATE TABLE IF NOT EXISTS "client"
(
    clientId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS "order"
(
    orderId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR (100),
    clientId BIGINT,
    placementDate DATE NOT NULL,
    closingDate DATE,
    phase INTEGER
);

CREATE TABLE IF NOT EXISTS "task"
(
    taskId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderId BIGINT,
    workerId BIGINT,
    jobId BIGINT,
    creatorWorkerId BIGINT,
    partFactor DOUBLE,
    time_create TIMESTAMP,
    comment VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS "worker"
(
    workerId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId BIGINT,
    firstName VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "user"
(
    userId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(20) NOT NULL ,
    passwordHash BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "job"
(
    jobId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "price"
(
    priceId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jobId BIGINT NOT NULL,
    client_price DOUBLE,
    worker_price DOUBLE,
    dateSince DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "equipment"
(
    equipmentId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientId BIGINT,
    addressId BIGINT,
    description VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS "address"
(
    addressId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(50),
    street VARCHAR(50),
    house VARCHAR(5),
    room VARCHAR(5)
);

ALTER TABLE "order"
ADD FOREIGN KEY (clientId) REFERENCES "client"(clientId);

ALTER TABLE "task"
ADD FOREIGN KEY (orderId) REFERENCES "order"(orderId);

ALTER TABLE "task"
ADD FOREIGN KEY (workerId) REFERENCES "worker"(workerId);

ALTER TABLE "task"
ADD FOREIGN KEY (jobId) REFERENCES "job"(jobId);

ALTER TABLE "task"
ADD FOREIGN KEY (creatorWorkerId) REFERENCES "worker"(workerId);

ALTER TABLE "worker"
ADD FOREIGN KEY (userId) REFERENCES "user"(userId);

ALTER TABLE "price"
ADD FOREIGN KEY (jobId) REFERENCES "job"(jobId);

ALTER TABLE "equipment"
ADD FOREIGN KEY (clientId) REFERENCES "client"(clientId);

ALTER TABLE "equipment"
ADD FOREIGN KEY (addressId) REFERENCES "address"(addressId);